// Based on https://github.com/happyleavesaoc/aoc-mgz/blob/master/mgz/enums.py

export const GAME_TYPES: Record<number, string> = {
  0: "Random Map",
  1: "Regicide",
  2: "Death Match",
  3: "Scenario",
  4: "Campaign",
  5: "King of the Hill",
  6: "Wonder Race",
  7: "Defend the Wonder",
  8: "Turbo Random Map",
  10: "Capture the Relic",
  11: "Sudden Death",
  12: "Battle Royale",
  13: "Empire Wars",
  15: "Co-op Campaign",
};

export const getGameTypeName = (id?: number) => (id !== undefined ? GAME_TYPES[id] : undefined);

export const VICTORY_TYPES: Record<number, string> = {
  0: "Standard",
  1: "Conquest",
  7: "Time Limit",
  8: "Score",
  11: "Last Man Standing",
};

export const getVictoryTypeName = (id?: number) => (id !== undefined ? VICTORY_TYPES[id] : undefined);

export const DIFFICULTY_TYPES: Record<number, string> = {
  0: "Hardest",
  1: "Hard",
  2: "Moderate",
  3: "Easy",
  4: "Very Easy",
  5: "Extreme",
};

export const getDifficultyName = (id?: number) => (id !== undefined ? DIFFICULTY_TYPES[id] : undefined);

export const MAP_SIZES: Record<number, string> = {
  // Map dimensions
  120: "Tiny (2 player)",
  144: "Small (3 player)",
  168: "Medium (4 player)",
  200: "Normal (6 player)",
  220: "Large (8 player)",
  240: "Giant",
  480: "Ludicrous",
};

export const getMapSizeName = (id?: number) => (id !== undefined ? MAP_SIZES[id] : undefined);

// Need a better mapping for map names

export const MAP_TYPES: Record<number, string> = {
  9: "Arabia",
  10: "Archipelago",
  11: "Baltic",
  12: "Black Forest",
  13: "Coastal",
  14: "Continental",
  15: "Crater Lake",
  16: "Fortress",
  17: "Gold Rush",
  18: "Highland",
  19: "Islands",
  20: "Mediterranean",
  21: "Migration",
  22: "Rivers",
  23: "Team Islands",
  24: "Full Random",
  25: "Scandinavia",
  26: "Mongolia",
  27: "Yucatan",
  28: "Salt Marsh",
  29: "Arena",
  31: "Ghost Lake",
  32: "Nomad",
  33: "Scandinavia (Alternate)",
  34: "Mongolia (Alternate)",
  35: "Yucatan (Alternate)",
  36: "Salt Marsh (Alternate)",
  37: "Arena (Alternate)",
  38: "King of the Hill",
  39: "Oasis",
  40: "Land Nomad",
  41: "Arid Arabia",
  44: "Lombardia",
  45: "Steppe",
  49: "Britain",
  50: "Byzantium",
  51: "Central America",
  52: "France",
  53: "Iberia",
  54: "Italy",
  55: "Mideast",
  56: "Japan",
  57: "Korea",
  58: "Middle East",
  60: "Golden Pit",
  62: "Hamburger",
  63: "Socotra",
  67: "Acropolis",
  68: "Budapest",
  69: "Cenotes",
  70: "City of Lakes",
  71: "Golden Swamp",
  72: "Magreb",
  73: "Nile Delta",
  74: "Serengeti",
  75: "Valley",
  100: "Border Stones",
  101: "Holy Line",
  110: "Snake Pit",
  122: "Alpine Lakes",
  123: "Bog Islands",
  124: "Mountain Pass",
  125: "Ravines",
  126: "Wolf Hill",
  132: "Pacific Islands",
  133: "Sandbank",
  137: "Custom Map",
  140: "Haboob",
  141: "Hideout",
  142: "Hill Fort",
  143: "Land Madness",
  144: "Northern Isles",
  145: "Ring of Reeds",
  146: "Marketplace",
  147: "Amazon Tunnel",
  148: "Coastal Forest",
  149: "African Clearing",
  150: "Atacama",
  151: "Bog Archipelago",
  152: "Crater",
  153: "Crossroads",
  154: "Enclosed",
  155: "Four Lakes",
  156: "Golden Hippo",
  157: "Acclivity",
  158: "Erdlend",
  168: "Aftermath",
  169: "Lakeside",
  170: "Pacific Islands (Alternate)",
};

export const getMapName = (id?: number) => (id !== undefined ? MAP_TYPES[id] : undefined);
